<?php

return [

    'menu_demos' => [
        [
            'route'    => 'demo',
            'title'    => 'Demo',
            'icon'     => 'ki-duotone ki-monitor-mobile fs-2',
            'paths'    => 2,
            'children' => [
                ['route' => 'demo.distribusi-widget', 'title' => 'Distribusi Widget'],
                [
                    'route'    => 'demo.sepuluhsatu',
                    'title'    => '01 - 10',
                    'children' => [
                        ['route' => 'demo.sepuluhsatu.demo1', 'title' => 'Satu'],
                        ['route' => 'demo.sepuluhsatu.demo2', 'title' => 'Dua'],
                        ['route' => 'demo.sepuluhsatu.demo3', 'title' => 'Tiga'],
                        ['route' => 'demo.sepuluhsatu.demo4', 'title' => 'Empat', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhsatu.demo5', 'title' => 'Lima'],
                        ['route' => 'demo.sepuluhsatu.demo6', 'title' => 'Enam', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhsatu.demo7', 'title' => 'Tujuh'],
                        ['route' => 'demo.sepuluhsatu.demo8', 'title' => 'Delapan'],
                        ['route' => 'demo.sepuluhsatu.demo9', 'title' => 'Sembilan'],
                        ['route' => 'demo.sepuluhsatu.demo10', 'title' => 'Sepuluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhdua',
                    'title'    => '11 - 20',
                    'children' => [
                        ['route' => 'demo.sepuluhdua.demo11', 'title' => 'Sebelas'],
                        ['route' => 'demo.sepuluhdua.demo12', 'title' => 'Dua Belas', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhdua.demo13', 'title' => 'Tiga Belas', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhdua.demo14', 'title' => 'Empat Belas'],
                        ['route' => 'demo.sepuluhdua.demo15', 'title' => 'Lima Belas'],
                        ['route' => 'demo.sepuluhdua.demo16', 'title' => 'Enam Belas'],
                        ['route' => 'demo.sepuluhdua.demo17', 'title' => 'Tujuh Belas'],
                        ['route' => 'demo.sepuluhdua.demo18', 'title' => 'Delapan Belas'],
                        ['route' => 'demo.sepuluhdua.demo19', 'title' => 'Sembilan Belas'],
                        ['route' => 'demo.sepuluhdua.demo20', 'title' => 'Dua Puluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhtiga',
                    'title'    => '21 - 30',
                    'children' => [
                        ['route' => 'demo.sepuluhtiga.demo21', 'title' => 'Dua Satu'],
                        ['route' => 'demo.sepuluhtiga.demo22', 'title' => 'Dua Dua'],
                        ['route' => 'demo.sepuluhtiga.demo23', 'title' => 'Dua Tiga'],
                        ['route' => 'demo.sepuluhtiga.demo24', 'title' => 'Dua Empat'],
                        ['route' => 'demo.sepuluhtiga.demo25', 'title' => 'Dua Lima'],
                        ['route' => 'demo.sepuluhtiga.demo26', 'title' => 'Dua Enam', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhtiga.demo27', 'title' => 'Dua Tujuh', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhtiga.demo28', 'title' => 'Dua Delapan'],
                        ['route' => 'demo.sepuluhtiga.demo29', 'title' => 'Dua Sembilan'],
                        ['route' => 'demo.sepuluhtiga.demo30', 'title' => 'Tiga Puluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhempat',
                    'title'    => '31 - 40',
                    'children' => [
                        ['route' => 'demo.sepuluhempat.demo31', 'title' => 'Tiga Satu'],
                        ['route' => 'demo.sepuluhempat.demo32', 'title' => 'Tiga Dua'],
                        ['route' => 'demo.sepuluhempat.demo33', 'title' => 'Tiga Tiga', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhempat.demo34', 'title' => 'Tiga Empat'],
                        ['route' => 'demo.sepuluhempat.demo35', 'title' => 'Tiga Lima', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhempat.demo36', 'title' => 'Tiga Enam', 'badge' => ['label' => 'Demo 1', 'class' => 'badge badge-primary']],
                        ['route' => 'demo.sepuluhempat.demo37', 'title' => 'Tiga Tujuh'],
                        ['route' => 'demo.sepuluhempat.demo38', 'title' => 'Tiga Delapan'],
                        ['route' => 'demo.sepuluhempat.demo39', 'title' => 'Tiga Sembilan'],
                        ['route' => 'demo.sepuluhempat.demo40', 'title' => 'Empat Puluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhlima',
                    'title'    => '41 - 50',
                    'children' => [
                        ['route' => 'demo.sepuluhlima.demo41', 'title' => 'Empat Satu'],
                        ['route' => 'demo.sepuluhlima.demo42', 'title' => 'Empat Dua'],
                        ['route' => 'demo.sepuluhlima.demo43', 'title' => 'Empat Tiga'],
                        ['route' => 'demo.sepuluhlima.demo44', 'title' => 'Empat Empat'],
                        ['route' => 'demo.sepuluhlima.demo45', 'title' => 'Empat Lima'],
                        ['route' => 'demo.sepuluhlima.demo46', 'title' => 'Empat Enam'],
                        ['route' => 'demo.sepuluhlima.demo47', 'title' => 'Empat Tujuh'],
                        ['route' => 'demo.sepuluhlima.demo48', 'title' => 'Empat Delapan'],
                        ['route' => 'demo.sepuluhlima.demo49', 'title' => 'Empat Sembilan'],
                        ['route' => 'demo.sepuluhlima.demo50', 'title' => 'Lima Puluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhenam',
                    'title'    => '51 - 60',
                    'children' => [
                        ['route' => 'demo.sepuluhenam.demo51', 'title' => 'Lima Satu'],
                        ['route' => 'demo.sepuluhenam.demo52', 'title' => 'Lima Dua'],
                        ['route' => 'demo.sepuluhenam.demo53', 'title' => 'Lima Tiga'],
                        ['route' => 'demo.sepuluhenam.demo54', 'title' => 'Lima Empat'],
                        ['route' => 'demo.sepuluhenam.demo55', 'title' => 'Lima Lima'],
                        ['route' => 'demo.sepuluhenam.demo56', 'title' => 'Lima Enam'],
                        ['route' => 'demo.sepuluhenam.demo57', 'title' => 'Lima Tujuh'],
                        ['route' => 'demo.sepuluhenam.demo58', 'title' => 'Lima Delapan'],
                        ['route' => 'demo.sepuluhenam.demo59', 'title' => 'Lima Sembilan'],
                        ['route' => 'demo.sepuluhenam.demo60', 'title' => 'Enam Puluh'],
                    ],
                ],
                [
                    'route'    => 'demo.sepuluhtujuh',
                    'title'    => '61 - 70',
                    'children' => [
                        ['route' => 'demo.sepuluhtujuh.demo61', 'title' => 'Enam Satu'],
                        ['route' => 'demo.sepuluhtujuh.demo62', 'title' => 'Enam Dua', 'badge' => ['label' => 'Soon', 'class' => 'badge badge-info']],
                        ['route' => 'demo.sepuluhtujuh.demo63', 'title' => 'Enam Tiga', 'badge' => ['label' => 'Soon', 'class' => 'badge badge-info']],
                        ['route' => 'demo.sepuluhtujuh.demo64', 'title' => 'Enam Empat', 'badge' => ['label' => 'Soon', 'class' => 'badge badge-info']],
                    ],
                ],
            ],
        ],
    ],
];
