<?php

return [
    'title' => 'Dukungan Aplikasi',
    'title_en' => 'App Support',
    'title_key' => 'md_app_support',
    'route' => 'datamaster.appsupport',
    'icon' => 'ki-duotone ki-abstract-28 fs-2',
    'paths' => 2,
    'permissions' => ['read'],
    'roles' => ['admin', 'master'],
    'children' => [
        [
            'title' => 'Menu',
            'title_en' => 'Menu',
            'title_key' => 'md_menu',
            'route' => 'datamaster.appsupport.menu',
            'permissions' => ['create', 'read', 'update', 'delete', 'sort'],
            'roles' => ['admin', 'master'],
        ],
        [
            'title' => 'Profil Aplikasi',
            'title_en' => 'App Profile',
            'title_key' => 'md_app_profil',
            'route' => 'datamaster.appsupport.app-profil',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['admin', 'master'],
        ],
        [
            'title' => 'Fitur Aplikasi',
            'title_en' => 'App Features',
            'title_key' => 'md_app_fitur',
            'route' => 'datamaster.appsupport.app-fiturs',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin', 'master'],
        ],
        [
            'title' => 'Backup DB',
            'title_en' => 'Database Backup',
            'title_key' => 'md_backup_db',
            'route' => 'datamaster.appsupport.backup-db',
            'permissions' => ['read'],
            'roles' => ['admin', 'master'],
        ],
        [
            'title' => 'Data Login',
            'title_en' => 'Login Data',
            'title_key' => 'md_data_login',
            'route' => 'datamaster.appsupport.data-login',
            'permissions' => ['read'],
            'roles' => ['admin', 'master'],
        ],
        [
            'title' => 'Tema Halaman Depan',
            'title_en' => 'Theme Front Page',
            'title_key' => 'md_theme_frontpage',
            'route' => 'datamaster.appsupport.theme-frontpage',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin', 'master'],
        ],
    ],
];
